- id: hlint
    name: hlint
    description: HLint gives suggestions on how to improve your source code.
    entry: hlint
    language: system
    files: '\.l?hs$'
- id: stylish-haskell
    name: stylish-haskell
    description: Haskell code prettifier.
    entry: stylish-haskell --inplace
    language: system
    files: '\.l?hs$'
